// treasury_codec.rs — Rust twin of src/treasuryTypes.ts (PR B of the company
// treasury plan): SSF deterministic CBOR, domain-tagged hashes, checkpoint vote
// tree, and proposal-window derivation. Both runtimes must produce byte-for-byte
// identical encodings before any hash becomes a policy or authorization
// commitment (plan §12) — proven against the shared vectors in
// ../test-vectors/treasury/, regenerated by test-vectors/treasury/generate.mjs.
//
// Encoding profile: RFC 8949 deterministic encoding, definite lengths only, no
// floats, no tags, no byte strings (binary travels as lowercase hex text),
// UTF-8 strings, shortest integer heads, map keys sorted bytewise by their
// encoded bytes. Arrays with SET semantics are sorted by canonical encoded
// bytes inside the hash helpers, exactly like the TypeScript side.
//
// Gated under `chia-lane` (CI compiles + tests it there). PR D's treasury
// module consumes these functions with typed structs; until then the helpers
// accept serde_json values so the golden-vector tests exercise the identical
// code path the fixtures were generated through.
#![allow(dead_code)]

use anyhow::{anyhow, bail, Result};
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::collections::BTreeSet;

// ---------------------------------------------------------------------------
// SSF deterministic CBOR
// ---------------------------------------------------------------------------

fn encode_head(major: u8, arg: u64, out: &mut Vec<u8>) {
    let base = major << 5;
    if arg < 24 {
        out.push(base | arg as u8);
    } else if arg < 0x100 {
        out.push(base | 24);
        out.push(arg as u8);
    } else if arg < 0x1_0000 {
        out.push(base | 25);
        out.extend_from_slice(&(arg as u16).to_be_bytes());
    } else if arg < 0x1_0000_0000 {
        out.push(base | 26);
        out.extend_from_slice(&(arg as u32).to_be_bytes());
    } else {
        out.push(base | 27);
        out.extend_from_slice(&arg.to_be_bytes());
    }
}

/// Encodes a JSON value under the SSF profile. Rejects floats — every number
/// in a treasury contract is an integer height/count/bps; amounts are decimal
/// strings (MojoString) precisely so they never ride JSON numbers.
pub fn canonical_encode(value: &Value) -> Result<Vec<u8>> {
    let mut out = Vec::new();
    encode_into(value, &mut out)?;
    Ok(out)
}

fn encode_into(value: &Value, out: &mut Vec<u8>) -> Result<()> {
    match value {
        Value::Null => out.push(0xf6),
        Value::Bool(false) => out.push(0xf4),
        Value::Bool(true) => out.push(0xf5),
        Value::Number(n) => {
            let i = n
                .as_i64()
                .ok_or_else(|| anyhow!("canonical_encode: only integers are encodable, got {n}"))?;
            // Mirror the JS safe-integer bound so both runtimes reject the
            // same inputs, not just encode the same accepted ones.
            const MAX_SAFE: i64 = 9_007_199_254_740_991;
            if !(-MAX_SAFE..=MAX_SAFE).contains(&i) {
                bail!("canonical_encode: integer outside JS safe range: {i}");
            }
            if i >= 0 {
                encode_head(0, i as u64, out);
            } else {
                encode_head(1, (-(i + 1)) as u64, out);
            }
        }
        Value::String(s) => {
            encode_head(3, s.len() as u64, out);
            out.extend_from_slice(s.as_bytes());
        }
        Value::Array(items) => {
            encode_head(4, items.len() as u64, out);
            for item in items {
                encode_into(item, out)?;
            }
        }
        Value::Object(map) => {
            let mut entries: Vec<(Vec<u8>, Vec<u8>)> = Vec::with_capacity(map.len());
            for (k, v) in map {
                let mut key_out = Vec::new();
                encode_into(&Value::String(k.clone()), &mut key_out)?;
                let mut val_out = Vec::new();
                encode_into(v, &mut val_out)?;
                entries.push((key_out, val_out));
            }
            entries.sort_by(|a, b| a.0.cmp(&b.0));
            encode_head(5, entries.len() as u64, out);
            for (k, v) in entries {
                out.extend_from_slice(&k);
                out.extend_from_slice(&v);
            }
        }
    }
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

/// sha256 over the canonical encoding, as lowercase hex.
pub fn canonical_hash_hex(value: &Value) -> Result<String> {
    Ok(sha256_hex(&canonical_encode(value)?))
}

/// Set-semantics arrays sort by their canonical encoded bytes before hashing.
pub fn sorted_set(values: &[Value]) -> Result<Vec<Value>> {
    let mut pairs: Vec<(Vec<u8>, Value)> = values
        .iter()
        .map(|v| Ok((canonical_encode(v)?, v.clone())))
        .collect::<Result<_>>()?;
    pairs.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(pairs.into_iter().map(|(_, v)| v).collect())
}

// ---------------------------------------------------------------------------
// Domain-tagged hashes (field-for-field mirrors of treasuryTypes.ts)
// ---------------------------------------------------------------------------

fn field<'a>(v: &'a Value, key: &str) -> Result<&'a Value> {
    v.get(key)
        .ok_or_else(|| anyhow!("treasury_codec: missing field \"{key}\""))
}

fn opt_or_null(v: &Value, key: &str) -> Value {
    v.get(key).cloned().unwrap_or(Value::Null)
}

fn share_class_canonical(class: &Value) -> Result<Value> {
    Ok(serde_json::json!({
        "id": field(class, "id")?,
        "assetId": field(class, "assetId")?,
        "votesPerWholeShare": field(class, "votesPerWholeShare")?,
        "grantsRoomAccess": field(class, "grantsRoomAccess")?,
        "transferable": field(class, "transferable")?,
        "convertsToClassId": opt_or_null(class, "convertsToClassId"),
        "sunsetHeight": opt_or_null(class, "sunsetHeight"),
    }))
}

const RULE_FIELDS: [&str; 9] = [
    "proposalThresholdBps",
    "passRule",
    "yesThresholdBps",
    "quorumBps",
    "vetoBps",
    "votingBlocks",
    "vetoBlocks",
    "implementationDelayBlocks",
    "executionWindowBlocks",
];

fn kind_rule_canonical(rule: &Value) -> Result<Value> {
    let mut out = serde_json::Map::new();
    for key in RULE_FIELDS {
        out.insert(key.to_string(), field(rule, key)?.clone());
    }
    Ok(Value::Object(out))
}

/// Mirrors policyHashOf(): every authority-bearing field, set arrays sorted,
/// optional fields normalized to explicit null (plan §12 + maxFeeMojos).
pub fn policy_hash_of(policy: &Value) -> Result<String> {
    let board = field(policy, "board")?;
    let signer_hashes = field(board, "signerPuzzleHashes")?
        .as_array()
        .ok_or_else(|| anyhow!("signerPuzzleHashes must be an array"))?;
    let share_classes = field(policy, "shareClasses")?
        .as_array()
        .ok_or_else(|| anyhow!("shareClasses must be an array"))?
        .iter()
        .map(share_class_canonical)
        .collect::<Result<Vec<_>>>()?;
    let approval_hashes = field(policy, "approvalModuleHashes")?
        .as_array()
        .ok_or_else(|| anyhow!("approvalModuleHashes must be an array"))?;
    let rules = field(policy, "governanceRules")?
        .as_object()
        .ok_or_else(|| anyhow!("governanceRules must be an object"))?;
    let mut rules_canonical = serde_json::Map::new();
    for (kind, rule) in rules {
        rules_canonical.insert(kind.clone(), kind_rule_canonical(rule)?);
    }
    canonical_hash_hex(&serde_json::json!({
        "domain": "ssf-company-treasury-policy:v1",
        "v": field(policy, "v")?,
        "networkGenesisChallenge": field(policy, "networkGenesisChallenge")?,
        "companyId": field(policy, "companyId")?,
        "treasuryLauncherId": field(policy, "treasuryLauncherId")?,
        "policyVersion": field(policy, "policyVersion")?,
        "board": {
            "threshold": field(board, "threshold")?,
            "signerPuzzleHashes": sorted_set(signer_hashes)?,
        },
        "shareClasses": sorted_set(&share_classes)?,
        "governanceRules": Value::Object(rules_canonical),
        "approvalModuleHashes": sorted_set(approval_hashes)?,
        "maxFeeMojos": field(policy, "maxFeeMojos")?,
        "emergencyPolicyHash": opt_or_null(policy, "emergencyPolicyHash"),
    }))
}

pub fn governance_rule_hash_of(kind: &str, rule: &Value) -> Result<String> {
    canonical_hash_hex(&serde_json::json!({
        "domain": "ssf-governance-rule:v1",
        "kind": kind,
        "rule": kind_rule_canonical(rule)?,
    }))
}

const PROPOSAL_FIELDS: [&str; 7] = [
    "v",
    "networkGenesisChallenge",
    "companyId",
    "policyVersion",
    "kind",
    "payloadHash",
    "proposerPub",
];

/// Non-recursive id over the UNSIGNED proposal body only (plan §7.1).
pub fn proposal_id_of(unsigned: &Value) -> Result<String> {
    let mut body = serde_json::Map::new();
    for key in PROPOSAL_FIELDS {
        body.insert(key.to_string(), field(unsigned, key)?.clone());
    }
    canonical_hash_hex(&serde_json::json!({
        "domain": "ssf-treasury-proposal:v1",
        "proposal": Value::Object(body),
    }))
}

pub fn proposal_signature_bytes(genesis: &str, proposal_id: &str) -> Result<Vec<u8>> {
    canonical_encode(&serde_json::json!({
        "domain": "ssf-treasury-proposal-signature:v1",
        "networkGenesisChallenge": genesis,
        "proposalId": proposal_id,
    }))
}

const VOTE_FIELDS: [&str; 8] = [
    "v",
    "networkGenesisChallenge",
    "proposalId",
    "voterPuzzleHash",
    "voterGamePub",
    "choice",
    "sequence",
    "chiaAddressProof",
];

pub fn vote_id_of(unsigned: &Value) -> Result<String> {
    let mut body = serde_json::Map::new();
    for key in VOTE_FIELDS {
        body.insert(key.to_string(), field(unsigned, key)?.clone());
    }
    canonical_hash_hex(&serde_json::json!({
        "domain": "ssf-treasury-vote:v1",
        "vote": Value::Object(body),
    }))
}

/// Mirrors voteSignatureBytes(): the bytes the voter's game key signs.
pub fn vote_signature_bytes(genesis: &str, vote_id: &str) -> Result<Vec<u8>> {
    canonical_encode(&serde_json::json!({
        "domain": "ssf-treasury-vote-signature:v1",
        "networkGenesisChallenge": genesis,
        "voteId": vote_id,
    }))
}

/// Mirrors payloadHashOf(): content address of a proposal payload — raw
/// sha256 over the bytes, which travel as non-empty lowercase hex text.
pub fn payload_hash_of(payload_hex: &str) -> Result<String> {
    if payload_hex.is_empty()
        || payload_hex.len() % 2 != 0
        || !payload_hex.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
    {
        bail!("payload_hash_of: payload must be non-empty lowercase hex bytes");
    }
    Ok(sha256_hex(&hex::decode(payload_hex)?))
}

const CHECKPOINT_FIELDS: [&str; 7] = [
    "v",
    "networkGenesisChallenge",
    "companyId",
    "proposalId",
    "voteRoot",
    "voteCount",
    "publisherPub",
];

pub fn checkpoint_id_of(body: &Value) -> Result<String> {
    let mut fields = serde_json::Map::new();
    for key in CHECKPOINT_FIELDS {
        fields.insert(key.to_string(), field(body, key)?.clone());
    }
    canonical_hash_hex(&serde_json::json!({
        "domain": "ssf-treasury-checkpoint:v1",
        "checkpoint": Value::Object(fields),
    }))
}

// ---------------------------------------------------------------------------
// Checkpoint vote tree (serverless plan §5)
// ---------------------------------------------------------------------------
// leaf = sha256(0x00 || vote_id_bytes); node = sha256(0x01 || left || right);
// distinct leaves sorted bytewise; an odd node is PROMOTED, never duplicated.

/// Mirrors TypeScript isHex32: exactly 64 LOWERCASE hex characters. Uppercase
/// would decode to the same bytes but survive string-level dedup/sort as a
/// distinct leaf, breaking the distinct-leaves-sorted-bytewise invariant.
fn is_hex32(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
}

fn merkle_leaf(vote_id: &str) -> Result<[u8; 32]> {
    if !is_hex32(vote_id) {
        bail!("vote_root_of: vote ids must be Hex32");
    }
    let bytes = hex::decode(vote_id)?;
    let mut hasher = Sha256::new();
    hasher.update([0x00]);
    hasher.update(&bytes);
    Ok(hasher.finalize().into())
}

fn merkle_node(left: &[u8; 32], right: &[u8; 32]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update([0x01]);
    hasher.update(left);
    hasher.update(right);
    hasher.finalize().into()
}

pub fn vote_root_of(vote_ids: &[String]) -> Result<String> {
    // Lowercase fixed-width hex sorts identically as strings and as bytes.
    let unique: BTreeSet<&String> = vote_ids.iter().collect();
    if unique.is_empty() {
        bail!("vote_root_of: a checkpoint must include at least one vote");
    }
    let mut level: Vec<[u8; 32]> = unique
        .into_iter()
        .map(|id| merkle_leaf(id))
        .collect::<Result<_>>()?;
    while level.len() > 1 {
        let mut next = Vec::with_capacity(level.len() / 2 + 1);
        let mut i = 0;
        while i + 1 < level.len() {
            next.push(merkle_node(&level[i], &level[i + 1]));
            i += 2;
        }
        if level.len() % 2 == 1 {
            next.push(level[level.len() - 1]);
        }
        level = next;
    }
    Ok(hex::encode(level[0]))
}

// ---------------------------------------------------------------------------
// Derived proposal windows (serverless plan §4)
// ---------------------------------------------------------------------------
// Pure function of the on-chain registration and the policy-committed rule —
// no serviceSig, nothing to trust. Every node derives identical deadlines.

const MAX_SAFE: i64 = 9_007_199_254_740_991;

/// Mirrors TypeScript isGovernanceKindRule field-for-field: bps fields are
/// integers in 0..=10000, passRule is one of the three enum strings, block
/// counts are integers in 0..=MAX_SAFE — so both runtimes reject the same
/// malformed rules, not just derive the same windows from accepted ones.
fn is_governance_kind_rule(rule: &Value) -> bool {
    let bps = |key: &str| -> bool {
        rule.get(key)
            .and_then(Value::as_i64)
            .is_some_and(|n| (0..=10_000).contains(&n))
    };
    let blocks = |key: &str| -> bool {
        rule.get(key)
            .and_then(Value::as_i64)
            .is_some_and(|n| (0..=MAX_SAFE).contains(&n))
    };
    let pass_rule = matches!(
        rule.get("passRule").and_then(Value::as_str),
        Some("majority-cast" | "supermajority-cast" | "supermajority-total-supply")
    );
    bps("proposalThresholdBps")
        && pass_rule
        && bps("yesThresholdBps")
        && bps("quorumBps")
        && bps("vetoBps")
        && blocks("votingBlocks")
        && blocks("vetoBlocks")
        && blocks("implementationDelayBlocks")
        && blocks("executionWindowBlocks")
}

pub fn derive_proposal_windows(registration: &Value, rule: &Value) -> Result<Value> {
    let accepted = field(registration, "acceptedHeight")?
        .as_i64()
        .ok_or_else(|| anyhow!("acceptedHeight must be an integer"))?;
    if !(0..=MAX_SAFE).contains(&accepted) {
        bail!("acceptedHeight is not a block height");
    }
    if !is_governance_kind_rule(rule) {
        bail!("derive_proposal_windows: malformed GovernanceKindRule");
    }
    let blocks = |key: &str| -> Result<i64> {
        field(rule, key)?
            .as_i64()
            .ok_or_else(|| anyhow!("{key} must be an integer"))
    };
    let add = |a: i64, b: i64| -> Result<i64> {
        a.checked_add(b)
            .ok_or_else(|| anyhow!("derive_proposal_windows: window heights overflow"))
    };
    let voting_ends = add(accepted, blocks("votingBlocks")?)?;
    let veto_ends = add(voting_ends, blocks("vetoBlocks")?)?;
    let executable_from = add(veto_ends, blocks("implementationDelayBlocks")?)?;
    let expires_after = add(executable_from, blocks("executionWindowBlocks")?)?;
    if expires_after > MAX_SAFE {
        bail!("derive_proposal_windows: window heights overflow");
    }
    let kind = field(registration, "kind")?
        .as_str()
        .ok_or_else(|| anyhow!("kind must be a string"))?;
    let accepted_block_hash = field(registration, "acceptedBlockHash")?;
    Ok(serde_json::json!({
        "v": 1,
        "proposalId": field(registration, "proposalId")?,
        "policyVersion": field(registration, "policyVersion")?,
        "governanceRuleHash": governance_rule_hash_of(kind, rule)?,
        "registrationCoinId": field(registration, "registrationCoinId")?,
        "acceptedHeight": accepted,
        "acceptedBlockHash": accepted_block_hash,
        // v1 rule: the share snapshot is pinned at the registration height.
        "snapshotHeight": accepted,
        "snapshotBlockHash": accepted_block_hash,
        "votingEndsHeight": voting_ends,
        "vetoEndsHeight": veto_ends,
        "executableFromHeight": executable_from,
        "expiresAfterHeight": expires_after,
    }))
}

// ---------------------------------------------------------------------------
// Golden-vector conformance tests (shared with src/treasuryTypes.test.ts)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod treasury_codec_tests {
    use super::*;

    const CBOR_VECTORS: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../test-vectors/treasury/canonical-cbor.json"
    );
    const CONTRACT_VECTORS: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../test-vectors/treasury/treasury-contracts.json"
    );

    fn load(path: &str) -> Value {
        let raw = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("cannot read vector file {path}: {e}"));
        serde_json::from_str(&raw).expect("vector file is valid JSON")
    }

    #[test]
    fn cbor_vectors_match_typescript() {
        let cases = load(CBOR_VECTORS);
        let cases = cases.as_array().expect("vector file is an array");
        assert!(cases.len() >= 30, "suspiciously few cbor cases");
        for case in cases {
            let name = case["name"].as_str().unwrap();
            let encoded = canonical_encode(&case["value"])
                .unwrap_or_else(|e| panic!("case {name} failed to encode: {e}"));
            assert_eq!(hex::encode(&encoded), case["hex"].as_str().unwrap(), "case {name}");
            assert_eq!(
                sha256_hex(&encoded),
                case["sha256"].as_str().unwrap(),
                "case {name} digest"
            );
        }
    }

    #[test]
    fn rejects_floats() {
        assert!(canonical_encode(&serde_json::json!(1.5)).is_err());
    }

    #[test]
    fn contract_hashes_match_typescript() {
        let v = load(CONTRACT_VECTORS);
        assert_eq!(
            policy_hash_of(&v["policy"]["value"]).unwrap(),
            v["policy"]["policyHash"].as_str().unwrap()
        );
        assert_eq!(
            governance_rule_hash_of(
                v["governanceRule"]["kind"].as_str().unwrap(),
                &v["governanceRule"]["rule"],
            )
            .unwrap(),
            v["governanceRule"]["governanceRuleHash"].as_str().unwrap()
        );
        assert_eq!(
            proposal_id_of(&v["proposal"]["unsigned"]).unwrap(),
            v["proposal"]["proposalId"].as_str().unwrap()
        );
        assert_eq!(
            hex::encode(
                proposal_signature_bytes(
                    v["proposal"]["unsigned"]["networkGenesisChallenge"].as_str().unwrap(),
                    v["proposal"]["proposalId"].as_str().unwrap(),
                )
                .unwrap()
            ),
            v["proposal"]["signatureBytesHex"].as_str().unwrap()
        );
        assert_eq!(
            vote_id_of(&v["vote"]["unsigned"]).unwrap(),
            v["vote"]["voteId"].as_str().unwrap()
        );
        assert_eq!(
            hex::encode(
                vote_signature_bytes(
                    v["vote"]["unsigned"]["networkGenesisChallenge"].as_str().unwrap(),
                    v["vote"]["voteId"].as_str().unwrap(),
                )
                .unwrap()
            ),
            v["vote"]["signatureBytesHex"].as_str().unwrap()
        );
        assert_eq!(
            checkpoint_id_of(&v["checkpoint"]["body"]).unwrap(),
            v["checkpoint"]["checkpointId"].as_str().unwrap()
        );
        assert_eq!(
            payload_hash_of(v["payload"]["payloadHex"].as_str().unwrap()).unwrap(),
            v["payload"]["payloadHash"].as_str().unwrap()
        );
        assert!(payload_hash_of("").is_err());
        assert!(payload_hash_of("abc").is_err());
        assert!(payload_hash_of("AB").is_err());
    }

    #[test]
    fn vote_tree_matches_typescript() {
        let v = load(CONTRACT_VECTORS);
        let ids: Vec<String> = v["voteTree"]["voteIds"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_str().unwrap().to_string())
            .collect();
        assert_eq!(
            vote_root_of(&ids).unwrap(),
            v["voteTree"]["voteRoot"].as_str().unwrap()
        );
        assert_eq!(
            vote_root_of(&[v["vote"]["voteId"].as_str().unwrap().to_string()]).unwrap(),
            v["voteTree"]["singleLeafRoot"].as_str().unwrap()
        );
        assert_eq!(
            vote_root_of(&ids[..2].to_vec().into_iter().rev().collect::<Vec<_>>()).unwrap(),
            v["voteTree"]["twoLeafRoot"].as_str().unwrap(),
            "root must be order-independent"
        );
        assert!(vote_root_of(&[]).is_err());
    }

    #[test]
    fn vote_tree_rejects_malformed_ids() {
        // Mirrors TypeScript voteRootOf: exactly 64 lowercase hex — decodable
        // hex of other shapes must not produce a root.
        assert!(vote_root_of(&["00".to_string()]).is_err());
        assert!(vote_root_of(&["A".repeat(64)]).is_err());
        assert!(vote_root_of(&[format!("A{}", "a".repeat(63))]).is_err());
    }

    #[test]
    fn window_derivation_rejects_malformed_input() {
        let v = load(CONTRACT_VECTORS);
        let reg = &v["windows"]["registration"];
        let rule = &v["windows"]["rule"];
        // acceptedHeight beyond the shared JS safe range is not a block height.
        let mut big = reg.clone();
        big["acceptedHeight"] = serde_json::json!(i64::MAX);
        assert!(derive_proposal_windows(&big, rule).is_err());
        // Heights that sum past MAX_SAFE overflow (mirrors the TS guard test).
        let mut near = reg.clone();
        near["acceptedHeight"] = serde_json::json!(MAX_SAFE - 10);
        assert!(derive_proposal_windows(&near, rule).is_err());
        // Rules TypeScript rejects must be rejected here too.
        let mut bad_bps = rule.clone();
        bad_bps["vetoBps"] = serde_json::json!(10_001);
        assert!(derive_proposal_windows(reg, &bad_bps).is_err());
        let mut bad_pass = rule.clone();
        bad_pass["passRule"] = serde_json::json!(42);
        assert!(derive_proposal_windows(reg, &bad_pass).is_err());
        let mut neg = rule.clone();
        neg["votingBlocks"] = serde_json::json!(-1);
        assert!(derive_proposal_windows(reg, &neg).is_err());
    }

    #[test]
    fn window_derivation_matches_typescript() {
        let v = load(CONTRACT_VECTORS);
        let derived =
            derive_proposal_windows(&v["windows"]["registration"], &v["windows"]["rule"]).unwrap();
        assert_eq!(derived, v["windows"]["derived"]);
    }

    #[test]
    fn sorted_set_matches_typescript() {
        let v = load(CONTRACT_VECTORS);
        let input: Vec<Value> = v["sortedSet"]["input"].as_array().unwrap().clone();
        assert_eq!(
            Value::Array(sorted_set(&input).unwrap()),
            v["sortedSet"]["output"]
        );
    }
}
